### ISSUE TITLE
To Do List (Project 4: Search Engine Part II)

### ISSUE THREAD

**Issue by DDKGM** [cop2805-bkj/cop2805-project3#11]
To Do:

File Operations
- [ ] Reading list of files
- [x] Must read a word at a time
- [x] Must check if previously index exist
- [x] Updating list of files
- [x] Store list of files in inverted index

Maintenance
- [x] Allows file selection for indexing
- [x] Must track files added
- [ ] Need full path name of the files as the file's last modification time 

Error-Handling
- [x] Must handle non-existent files
- [x] Must handle unreadable files

**Comment by Xinnx** [comment]
I have checked off error handling because the classes I use to create the InvertedIndexes do so when
instantiated and throw applicable exceptions. Also the file chooser only allows the user to input .txt files. so to get a invalid file into the indexer you would have to modify the settings.json before opening the application.

The rest of these features are included in my index implementation branch.

**Comment by Nivirx** [comment]
I didn't check "need full path name..." because the full path name is stored internally, I might make the change so if you click on the box it will toggle between short-hand and long-hand, but I felt that just the filename + extension was cleaner because of space concerns (at least on unix systems where you can get pretty long path names like /home/bclaus/Documents/workplace/cop_project3/res/textfile.txt and the same could be said for windows systems). 

I am going to close this for now just to check off _most_ of the boxes for our required parts.

feel free to reopen it
